### PR TITLE
Lasb 766

### PR DESCRIPTION
**Pull request by lucas-e-t**
## What

[Link to story](https://dsdmoj.atlassian.net/browse/LASB-766)

Describe what you did and why:

I've created CurrentStatus enum to contain the same two static values held in DB tables:    HARDSHIP_REVIEW_STATUSES, IOJ_APPEAL_STATUSES, FIN_ASS_STATUSES.

I've also created CurrentStatus for mapping enum value to DB and vice versa.

I've also added test coverage for FrequencyConverter.

## Checklist

Before you ask people to review this PR:

- [x] Tests should be passing: `./gradlew test`
- [x] Github should not be reporting conflicts; you should have recently run `git rebase master`.
- [x] Avoid mixing whitespace changes with code changes in the same commit. These make diffs harder to read and conflicts more likely.
- [x] You should have looked at the diff against master and ensured that nothing unexpected is included in your changes.
- [x] You should have checked that the commit messages say why the change was made.

### CODE REVIEW

**Review by rajkrk — CHANGES_REQUESTED** [review]
@lucas-e-t  The converters for enums do not have unit tests, please can you address ? Also please add a comment on this class mentioning the tables it is replacing.

**Review by lucas-e-t — COMMENTED** [review]
I've added unit tests for converters and I've added reference to table names on Enums

**Review by msahilan07 — APPROVED** [review]
LGTM

**Review by msahilan07 — APPROVED** [review]

**Review by rajkrk — APPROVED** [review]
Please merge

**Pull request merged**
